language: java
sudo: true
jdk:
  - openjdk8

# https://docs.codacy.com/coverage-reporter/adding-coverage-to-your-repository/
export CODACY_PROJECT_TOKEN=28aa1f95f0534ce9b287310fffa079e8
export CODACY_API_BASE_URL=https://app.codacy.com/manual/yansheng836/wzry2

before_install:
  - chmod +x mvnw

# codecov
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
